name: Publish Helm Chart

on:
  push:
    branches:
      - main
      - master

jobs:
  helm-chart-push:
    runs-on: docker
    env:
      HARBOR_USERNAME: "robot$zimbra+robot"
      HARBOR_PASSWORD: ${{ secrets.HARBOR_TOKEN }}
      DOCKER_HUB_REPO: "zimbra/docker-zimbra-chart"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.13.0

      - name: Log in to Docker Hub (Helm OCI)
        run: |
          echo $HARBOR_PASSWORD | helm registry login harbor-pve1.spbnix.local \
            --username $HARBOR_USERNAME --password-stdin

      - name: Package Helm chart
        run: |
          helm package .

      - name: Push Helm chart to Docker Hub
        run: |
          CHART_PACKAGE=$(ls *.tgz | head -n 1)
          helm push $CHART_PACKAGE oci://harbor-pve1.spbnix.local/${DOCKER_HUB_REPO}
