{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.externalHostFQDN }}
    secretName: tls-{{ .Values.externalHostFQDN | replace "." "-" }}
  rules:
  - host: {{ .Values.externalHostFQDN }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "service.fullname" . }}
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
{{- end }}