{{- if .Values.admin.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "service.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  {{- with .Values.admin.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.admin.ingress.host }}
    secretName: tls-{{ .Values.admin.ingress.host | replace "." "-" }}
  rules:
  - host: {{ .Values.admin.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "service.fullname" . }}
            port:
              number: 9071
        path: /
        pathType: ImplementationSpecific
{{- end }}