apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ include "service.name" . }}
  name: {{ include "service.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "service.name" . }}
  serviceName: {{ include "service.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "service.name" . }}
      annotations:
        container.apparmor.security.beta.kubernetes.io/zimbra: unconfined
        container.seccomp.security.alpha.kubernetes.io/zimbra: unconfined
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 180
      containers:
      - name: zimbra
        image: {{ .Values.image }}:{{ .Values.tag }}
        imagePullPolicy: Always
        env:
        - name: EXTERNAL_HOST_FQDN
          value: {{ .Values.externalHostFQDN }}
        - name: MAIL_DOMAINS
          value: {{ .Values.mailDomains }}
        volumeMounts:
        - name: zimbra
          mountPath: /data
        - name: tls-certs
          mountPath: /data/app/tls
          readOnly: true
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_PTRACE
      volumes:
      - name: tls-certs
        secret:
          secretName: {{ include "service.fullname" . }}-tls
          items:
          - key: tls.key
            path: zimbra.key
          - key: tls.crt
            path: zimbra.crt
  volumeClaimTemplates:
  - metadata:
      name: zimbra
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.storageClassName }}
      storageClassName: {{ .Values.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.storageRequests }}